title:
  en: "Your Title"
subtitle:
  en: "Your Description"

#-----------------------------------------------

domain:
  production: 'localhost'
  staging: 'staging.localhost'

language:
  default:
    key: 'en'
    value: 'English'
