version: '2'
services:
  build:
    image: agneta-build
    build:
      context: .
    volumes:
      - .:/home/app
    working_dir: /home/app
    command: agneta image build -m portal
  dev:
    domainname: '<%-config.domain%>'
    hostname: '<%-config.domain%>'
    image: '<%-config.image%>'
    build:
      context: .
    environment:
      - USER=<%-config.user.username%>
      - USER_ID=<%-config.user.uid%>
      - GROUP_ID=<%-config.user.gid%>
      - NODE_ENV=development
      - MODE=portal
      - HOST_NAME=<%-config.domain%>
      - PORT_HTTP=<%-config.portHttp%>
      - PORT=<%-config.port%>
    ports:
      - '<%-config.portHttp%>:80'
      - '<%-config.port%>:443'
    volumes:
      - .:<%-config.path.app%>
      - <%-config.path.projectCli%>:/usr/local/lib/node_modules/agneta-cli
      - <%-config.path.projectPlatform%>:<%-config.path.app%>/node_modules/agneta-platform
      - <%-config.path.app%>/node_modules/uws
      - <%-config.path.app%>/node_modules/agneta-platform/node_modules/uws
