version: '2'
services:
  build:
    image: agneta-build
    build:
      context: .
    environment:
      - NODE_ENV=development
      - MODE=portal
    volumes:
      - .:/home/app
    working_dir: /home/app
    command: agneta image build -m dev
  dev:
    image: '<%-config.image%>'
    build:
      context: .
    environment:
      - NODE_ENV=development
      - MODE=portal
      - PORT=<%-config.port%>
    ports:
      - '<%-config.port%>:<%-config.port%>'
    volumes:
      - .:<%-config.path.app%>
      - <%-cliPath%>:/usr/local/lib/node_modules/agneta-cli
      - <%-platformPath%>:<%-config.path.app%>/node_modules/agneta-platform
      - <%-config.path.app%>/node_modules/uws
      - <%-config.path.app%>/node_modules/agneta-platform/node_modules/uws
