FROM node:8-alpine

RUN apk -v --update add \
        python \
        openssh \
        build-base \
        libssh-dev \
        git \
        graphicsmagick \
        bash \
        libc6-compat \
        gawk \
        sed \
        grep \
        bc \
        coreutils \
        su-exec \
        && \
    apk -v --purge del py-pip && \
    rm /var/cache/apk/*

# Enviroment variables

ARG AGNETA_SECRET_KEY=3

#RUN npm config set registry $REGISTRY
RUN npm config set registry https://registry.npmjs.org/
RUN npm config set cache /.cache/npm --global
<%-config.commands.cli%>


COPY . <%-config.path.app%>

WORKDIR <%-config.path.app%>

RUN agneta image setup

# Copy npm cache and install packages
<%-config.commands.npm%>

ADD package.json package-lock.json /tmp/
RUN cd /tmp && npm install --prefer-offline --loglevel info
RUN mkdir -p <%-config.path.app%> && cd <%-config.path.app%> && ln -s /tmp/node_modules

# Start Agneta
ENV HOME=<%-config.path.home%>

RUN chmod +x <%-config.path.app%>/entrypoint.sh
ENTRYPOINT ["<%-config.path.app%>/entrypoint.sh"]
CMD ["agneta", "process", "start"]
