FROM <%-config.image.base%>

ARG AGNETA_SECRET_KEY=3

COPY --chown=<%-config.user.username%>:<%-config.user.username%> . <%-config.path.app%>

RUN npm install --prefer-offline --no-shrinkwrap --loglevel info && \
    npm run setup

CMD ["agneta", "process", "start"]
