FROM agneta/base:latest
ARG AGNETA_SECRET_KEY=3
ENV PATH "$PATH:/home/agneta/.npm-global/bin"
COPY --chown=agneta:agneta . /home/agneta/app

RUN npm ci --global --prefer-offline --no-shrinkwrap --loglevel info --only=production @agneta/cli && \
    npm ci --prefer-offline --no-shrinkwrap --loglevel info --only=production && \
    agneta image setup

CMD ["agneta", "start"]