FROM node:8-alpine

RUN apk -v --update add \
    python \
    openssh \
    build-base \
    libssh-dev \
    git \
    graphicsmagick \
    bash \
    libc6-compat \
    gawk \
    sed \
    grep \
    bc \
    coreutils \
    su-exec && \
    apk -v --purge del py-pip && \
    rm /var/cache/apk/* && \
    mkdir -p <%-config.path.app%>

WORKDIR <%-config.path.app%>

RUN <%-config.commands.installAgnetaCli%> && \
    npm config set cache <%-config.path.home%>/.cache/npm --global && \
    npm config set package-lock false && \
    export HOME=<%-config.path.home%> && \
    export USER=<%-config.user.username%> && \
    export USER_ID=<%-config.user.uid%> && \
    export GROUP_ID=<%-config.user.gid%> && \
    USER_ID=${USER_ID:-9001} && \
    GROUP_ID=${GROUP_ID:-9001} && \
    deluser --remove-home node && \
    addgroup -S -g $GROUP_ID $USER && \
    adduser -S -u $USER_ID -G $USER $USER && \
    chown -R $USER:$USER $HOME

USER <%-config.user.username%>
