FROM agneta/base

ARG AGNETA_SECRET_KEY=3

COPY . <%-config.path.app%>
RUN npm install --prefer-offline --no-shrinkwrap --loglevel info && \
    echo "\"${AGNETA_SECRET_KEY}\"" >> <%-config.path.home%>/secret.json

CMD ["agneta", "process", "start"]
