FROM agneta/base

ARG AGNETA_SECRET_KEY=3

COPY --chown=<%-config.user.username%>:<%-config.user.username%> . <%-config.path.app%>

RUN agneta image setup && \
    npm install --prefer-offline --no-shrinkwrap --loglevel info && \
    echo "\"${AGNETA_SECRET_KEY}\"" >> <%-config.path.home%>/secret.json

CMD ["agneta", "process", "start"]
